python -W ignore::UserWarning -m mask_cyclegan_vc.train \
    --name mask_cyclegan_vc_takion_suzuka \
    --seed 0 \
    --save_dir results/ \
    --preprocessed_data_dir converted_data \
    --speaker_A_id takion \
    --speaker_B_id suzuka \
    --epochs_per_save 20 \
    --epochs_per_plot 10 \
    --num_epochs 6172 \
    --batch_size 1 \
    --lr 5e-4 \
    --decay_after 1e4 \
    --sample_rate 22050 \
    --num_frames 64 \
    --max_mask_len 25 \
    --gpu_ids 0 \
